# Generated by Django 2.2.7 on 2020-01-22 09:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('pk_courseid', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('pk_clubid', models.AutoField(primary_key=True, serialize=False)),
                ('club', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'club',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('pk_countryid', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('pk_course_typeid', models.AutoField(primary_key=True, serialize=False)),
                ('hand_index', models.CharField(blank=True, max_length=45, null=True)),
                ('course_handicap', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('fk_courseid', models.ForeignKey(db_column='fk_courseid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='types', to='backend.Course')),
            ],
            options={
                'db_table': 'course_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DrawType',
            fields=[
                ('pk_draw_typeid', models.AutoField(primary_key=True, serialize=False)),
                ('draw_type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'draw_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('pk_eventid', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=500)),
                ('event_description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('fk_draw_typeid', models.ForeignKey(db_column='fk_draw_typeid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.DrawType')),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('pk_event_typeid', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'event_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('pk_fieldid', models.AutoField(primary_key=True, serialize=False)),
                ('field_type', models.CharField(max_length=3)),
                ('fk_eventid', models.ForeignKey(db_column='fk_eventid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='field', to='backend.Event')),
            ],
            options={
                'db_table': 'field',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('pk_formatid', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'format',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('pk_genderid', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gender',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('pk_holeid', models.AutoField(primary_key=True, serialize=False)),
                ('hole', models.IntegerField()),
            ],
            options={
                'db_table': 'hole',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('pk_permissionid', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=20)),
                ('permission_desc', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'permission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pk_profileid', models.AutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=45)),
                ('fk_genderid', models.ForeignKey(db_column='fk_genderid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Gender')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('pk_roleid', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=45)),
                ('role_desc', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SlotSize',
            fields=[
                ('pk_slot_sizeid', models.AutoField(primary_key=True, serialize=False)),
                ('slot_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'slot_size',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('pk_typeid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('pk_slotid', models.AutoField(primary_key=True, serialize=False)),
                ('slot_time', models.TimeField()),
                ('day', models.IntegerField()),
                ('fk_fieldid', models.ForeignKey(db_column='fk_fieldid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='slots', to='backend.Field')),
            ],
            options={
                'db_table': 'slot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('pk_role_permissionid', models.AutoField(primary_key=True, serialize=False)),
                ('fk_permissionid', models.ForeignKey(db_column='fk_permissionid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Permission')),
                ('fk_roleid', models.ForeignKey(db_column='fk_roleid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Role')),
            ],
            options={
                'db_table': 'role_permission',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='role',
            name='Permissions',
            field=models.ManyToManyField(related_name='permissions', through='backend.RolePermission', to='backend.Permission'),
        ),
        migrations.CreateModel(
            name='RegistrationDate',
            fields=[
                ('pk_registration_dateid', models.AutoField(primary_key=True, serialize=False)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('fk_eventid', models.ForeignKey(db_column='fk_eventid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='registrationDate', to='backend.Event')),
            ],
            options={
                'db_table': 'registration_date',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('pk_registerid', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fk_profileid', models.ForeignKey(db_column='fk_profileid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='backend.Profile')),
                ('fk_slot_sizeid', models.ForeignKey(db_column='fk_sizeid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.SlotSize')),
                ('fk_slotid', models.ForeignKey(db_column='fk_slotid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='registers', to='backend.Slot')),
            ],
            options={
                'db_table': 'register',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfileRole',
            fields=[
                ('pk_profile_roleid', models.AutoField(primary_key=True, serialize=False)),
                ('fk_profileid', models.ForeignKey(db_column='fk_profileid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Profile')),
                ('fk_roleid', models.ForeignKey(db_column='fk_roleid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Role')),
            ],
            options={
                'db_table': 'profile_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('pk_informationid', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('fk_eventid', models.ForeignKey(db_column='fk_eventid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='information', to='backend.Event')),
            ],
            options={
                'db_table': 'information',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('pk_handicapid', models.AutoField(primary_key=True, serialize=False)),
                ('handicap_index', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField()),
                ('date', models.DateField()),
                ('fk_profileid', models.ForeignKey(db_column='fk_profileid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Profile')),
            ],
            options={
                'db_table': 'handicap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('pk_event_formatid', models.AutoField(primary_key=True, serialize=False)),
                ('fk_eventid', models.ForeignKey(db_column='fk_eventid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventFormat', to='backend.Event')),
                ('fk_formatid', models.ForeignKey(db_column='fk_formatid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Format')),
            ],
            options={
                'db_table': 'event_format',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='fk_event_typeid',
            field=models.ForeignKey(db_column='fk_event_typeid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='fk_profileid',
            field=models.ForeignKey(db_column='fk_profileid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Profile'),
        ),
        migrations.CreateModel(
            name='CourseTypeHole',
            fields=[
                ('pk_course_type_holeid', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('par', models.IntegerField()),
                ('si', models.IntegerField(blank=True, null=True)),
                ('fk_course_typeid', models.ForeignKey(db_column='fk_course_typeid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='holes', to='backend.CourseType')),
                ('hole_pk_holeid', models.ForeignKey(db_column='hole_pk_holeid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Hole')),
            ],
            options={
                'db_table': 'course_type_hole',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='coursetype',
            name='fk_typeid',
            field=models.ForeignKey(db_column='fk_typeid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Type'),
        ),
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('pk_club_profileid', models.AutoField(primary_key=True, serialize=False)),
                ('fk_clubid', models.ForeignKey(db_column='fk_clubid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Club')),
                ('fk_profileid', models.ForeignKey(db_column='fk_profileid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Profile')),
            ],
            options={
                'db_table': 'club_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClubCourse',
            fields=[
                ('pk_club_courseid', models.AutoField(primary_key=True, serialize=False)),
                ('fk_clubid', models.ForeignKey(db_column='fk_clubid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Club')),
                ('fk_courseid', models.ForeignKey(db_column='fk_courseid', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Course')),
            ],
            options={
                'db_table': 'club_course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('pk_ratingid', models.AutoField(primary_key=True, serialize=False)),
                ('course_rating', models.CharField(max_length=45)),
                ('sloppy_rating', models.CharField(max_length=45)),
                ('par', models.CharField(blank=True, max_length=45, null=True)),
                ('fk_courseid', models.ForeignKey(db_column='fk_courseid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rating', to='backend.Course')),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
                'unique_together': {('pk_ratingid', 'fk_courseid')},
            },
        ),
    ]
