# Generated by Django 2.2.7 on 2019-12-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('pk_slot_activityid', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(blank=True, max_length=45, null=True)),
                ('slot_status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('pk_clubid', models.AutoField(primary_key=True, serialize=False)),
                ('club', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'club',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubCourse',
            fields=[
                ('pk_club_courseid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'club_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('pk_club_profileid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'club_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('pk_countryid', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('pk_courseid', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('pk_course_typeid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'course_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseTypeHole',
            fields=[
                ('pk_course_type_holeid', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('par', models.IntegerField()),
                ('si', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course_type_hole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('pk_eventid', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=500)),
                ('event_description', models.CharField(max_length=45)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('pk_event_dayid', models.AutoField(primary_key=True, serialize=False)),
                ('event_day', models.DateField()),
            ],
            options={
                'db_table': 'event_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('pk_event_formatid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'event_format',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('pk_event_typeid', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'event_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('pk_formatid', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'format',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Handcap',
            fields=[
                ('pk_handcapid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'handcap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('pk_holeid', models.IntegerField(primary_key=True, serialize=False)),
                ('hole', models.IntegerField()),
            ],
            options={
                'db_table': 'hole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('pk_permissionid', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=20)),
                ('permission_desc', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pk_profileid', models.AutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileRole',
            fields=[
                ('pk_profile_roleid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profile_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('pk_ratingid', models.AutoField(primary_key=True, serialize=False)),
                ('course_rating', models.CharField(max_length=45)),
                ('sloppy_rating', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('pk_registerid', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationDate',
            fields=[
                ('pk_registration_dateid', models.AutoField(primary_key=True, serialize=False)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'registration_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('pk_roleid', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=45)),
                ('role_desc', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('pk_role_permissionid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'role_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('pk_slotid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'slot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('pk_typeid', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
    ]
