# Generated by Django 2.2.7 on 2019-12-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191210_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('pk_handicapid', models.AutoField(primary_key=True, serialize=False)),
                ('handicap_index', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'handicap',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Handcap',
        ),
    ]
